language: ruby
cache: bundler
sudo: required
rvm:
  - 2.5
  - 2.6
services:
  - mongodb
branches:
  only:
  - master
notifications:
  email:
    recipients:
      - fhir-testing-list@lists.mitre.org
    on_failure: change
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - npm -g install bower
  - bower install
  - npm install -g istanbul
script:
  - ./bin/rake test
  - ./bin/teaspoon
