development:
  sessions:
    default:
      database: crucible_development
      hosts:
        - <%= ENV['MONGODB_HOST'] || "localhost:27017" %>
test:
  sessions:
    default:
      database: crucible_test
      hosts:
        - <%= ENV['MONGODB_HOST'] || "localhost:27017" %>
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: crucible_production
      hosts:
        - <%= ENV['MONGODB_HOST'] || "localhost:27017" %>
